import Head from 'next/head'
import type { NextPage } from 'next'

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>stkzer | List </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </>
  )
}

export default Index
