import Head from 'next/head'

import type { NextPage } from 'next'
import Auth from 'modules/login/Auth'
import { StyledAuthCol, StyledAuthRow } from 'theme/auth.element'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>stkzer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <StyledAuthRow>
        <StyledAuthCol>
          <Auth />
        </StyledAuthCol>
        <StyledAuthCol />
      </StyledAuthRow>
    </>
  )
}

export default Home
