import Head from 'next/head'
import type { NextPage } from 'next'

import Input from 'modules/input/Input'
import Button from 'modules/button/Button'

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>stkzer | List </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <>
        <Input type={'text'} label={'adding a new list'} />
        <Button title={'create'} background={'#3b82f6'} color={'a'} />
      </>
    </>
  )
}

export default Index
