import Head from 'next/head'
import Image from 'next/image'
import type { NextPage } from 'next'
import Button from 'modules/button/Button'

import { BsArrowRightShort } from 'react-icons/bs'
import { motion } from 'framer-motion'
import {
  Banner,
  Column,
  HeadingParag,
  HeadingTitle,
} from 'theme/banner.element'

import { useRouter } from 'next/router'
import { __auth } from 'context/AuthProvider'

const Home: NextPage = () => {
  const { push } = useRouter()
  const { isLoggedIn } = __auth()

  return (
    <>
      <Head>
        <title>stkzer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/svg/icon.svg' />
      </Head>

      <Banner>
        <Column>
          <div>
            <HeadingTitle>a one place for all your lists</HeadingTitle>
            <HeadingParag>
              We started as a place to store your watchlist since streaming
              services works idependently and you can eassily can get lost, now
              you can save up all your list from books to cooking recipies, and
              easily keep track of them.
            </HeadingParag>
            <br />
            {isLoggedIn ? (
              <Button
                title={'get started'}
                onClick={() => push('/profile')}
                textTransform={'UP'}
                icon={<BsArrowRightShort size={24} />}
              />
            ) : (
              <Button
                title={'get started'}
                textTransform={'UP'}
                onClick={() => push('/auth')}
                icon={<BsArrowRightShort size={24} />}
              />
            )}
          </div>
        </Column>
        <Column>
          <motion.div
            initial={{ y: -10 }}
            animate={{ y: 14 }}
            transition={{
              duration: 3,
              repeat: Infinity,
              repeatType: 'reverse',
            }}
            viewport={{ once: true }}>
            <Image
              priority
              width={425}
              height={450}
              src={'/svg/banner.svg'}
              alt={'banner on what stkzer contains'}
            />
          </motion.div>
        </Column>
      </Banner>
    </>
  )
}

export default Home
